specVersion: "0.2.0"

name: "Bloody Valentine by Neon Crisis"
version: "1.0.0"
description: "VDay Card Transactions"
repository: "https://github.com/boostdmg01/moonbeans-bot"

schema:
  file: "./schema.graphql"

network:
  genesisHash: '0x401a1f9dca3da46f5c4091016c8a2f26dcea05865116b286f60f668207d1474b' # Genesis hash of Moonriver
  endpoint: wss://moonriver.api.onfinality.io/public-ws

  chaintypes:
    file: "./types.yaml"

dataSources:
  - kind: substrate/Moonbeam
    startBlock: 1482028
    processor:
      file: './node_modules/@subql/contract-processors/dist/moonbeam.js'
      options:
        abi: contract
        address: '0x366140C861fcC3694F3b6FA83DeBB78d39B14BFe'
    assets:
      contract:
        file: './vdaycard.abi.json'
    mapping:
      file: './dist/index.js'
      handlers:
        - handler: handleSafeTransferFrom
          kind: substrate/MoonbeamCall
          filter:
            function: safeTransferFrom(address,address,uint256,string,string)
        - handler: handleRespond
          kind: substrate/MoonbeamCall
          filter:
            function: respond(uint256,bool,string,string)
